import 'dart:convert';
import 'package:google_generative_ai/google_generative_ai.dart';
import '../constants/app_constants.dart';

class GeminiService {
  static GeminiService? _instance;
  GenerativeModel? _model;

  GeminiService._();

  static GeminiService get instance {
    _instance ??= GeminiService._();
    return _instance!;
  }

  void initialize(String apiKey) {
    _model = GenerativeModel(
      model: AppConstants.geminiModel,
      apiKey: apiKey,
      generationConfig: GenerationConfig(
        temperature: 0.3,
        topK: 40,
        topP: 0.95,
        maxOutputTokens: 8192,
      ),
    );
  }

  GenerativeModel get model {
    if (_model == null) {
      throw StateError(
        'GeminiService not initialized. Call initialize(apiKey) first.',
      );
    }
    return _model!;
  }

  /// Analyze text for AI content detection
  Future<Map<String, dynamic>> detectAiContent(String text) async {
    print('GeminiService: Starting AI content detection');
    final prompt = '''
Analyze the following text and determine if it was written by a human or generated by AI.

Text to analyze:
"""
$text
"""

Respond ONLY with valid JSON in this exact format:
{
  "human_score": <0-100>,
  "ai_score": <0-100>,
  "confidence": <0-100>,
  "content_type": "<human|ai|mixed>",
  "reasoning": "<brief explanation>",
  "ai_indicators": ["<indicator1>", "<indicator2>"],
  "human_indicators": ["<indicator1>", "<indicator2>"]
}

Scoring guidelines:
- human_score + ai_score = 100
- content_type is "human" if ai_score < 30, "ai" if ai_score > 70, "mixed" otherwise
- confidence is how certain you are (0-100)
''';

    try {
      final response = await model.generateContent([Content.text(prompt)]);
      final textResponse = response.text ?? '{}';
      print('GeminiService: Received AI detection response');
      final jsonStr = _extractJson(textResponse);
      return jsonDecode(jsonStr) as Map<String, dynamic>;
    } catch (e) {
      print('GeminiService Error (AI Detection): $e');
      return {
        'human_score': 70,
        'ai_score': 30,
        'confidence': 50,
        'content_type': 'human',
        'reasoning': 'Unable to analyze content at this time.',
        'ai_indicators': [],
        'human_indicators': [],
      };
    }
  }

  /// Analyze text for writing quality
  Future<Map<String, dynamic>> analyzeWritingQuality(String text) async {
    print('GeminiService: Starting writing quality analysis');
    final prompt = '''
Analyze the writing quality of the following academic text.

Text:
"""
$text
"""

Respond ONLY with valid JSON:
{
  "grammar_score": <0-100>,
  "readability_score": <0-100>,
  "academic_tone_score": <0-100>,
  "vocabulary_score": <0-100>,
  "structure_score": <0-100>,
  "overall_writing_score": <0-100>,
  "grammar_issues": [
    {"issue": "<description>", "example": "<text>", "correction": "<corrected>", "tip": "<learning tip>"}
  ],
  "tone_issues": [
    {"issue": "<description>", "example": "<text>", "suggestion": "<better version>"}
  ],
  "vocabulary_suggestions": [
    {"word": "<word>", "suggestion": "<better word>", "reason": "<why>"}
  ],
  "structure_suggestions": ["<suggestion>"],
  "learning_tips": ["<tip>"],
  "flesch_score": <0-100>,
  "avg_sentence_length": <number>,
  "passive_voice_percentage": <0-100>,
  "academic_word_percentage": <0-100>
}
''';

    try {
      final response = await model.generateContent([Content.text(prompt)]);
      final responseText = response.text ?? '{}';
      print('GeminiService: Received quality analysis response');
      final jsonStr = _extractJson(responseText);
      return jsonDecode(jsonStr) as Map<String, dynamic>;
    } catch (e) {
      print('GeminiService Error (Quality): $e');
      return {
        'grammar_score': 75,
        'readability_score': 70,
        'academic_tone_score': 65,
        'vocabulary_score': 70,
        'structure_score': 72,
        'overall_writing_score': 70,
        'grammar_issues': [],
        'tone_issues': [],
        'vocabulary_suggestions': [],
        'structure_suggestions': [],
        'learning_tips': ['Focus on clear, concise academic writing.'],
      };
    }
  }

  /// Detect plagiarism semantically and explain flagged sections
  Future<Map<String, dynamic>> analyzeForPlagiarism(
    String text,
    List<Map<String, dynamic>> webSources,
  ) async {
    print('GeminiService: Starting plagiarism analysis');
    final sourcesJson = jsonEncode(webSources.take(10).toList());

    final prompt = '''
You are an expert plagiarism detection system. Analyze the following text against the provided web sources and your internal knowledge of the web.

CRITICAL INSTRUCTIONS:
1. If the text is a direct copy from a common website (like Google, Wikipedia, or news articles), the "overall_similarity_score" MUST be near 100%.
2. Identify the specific sources where this text appears.
3. Be strict. Paraphrasing that keeps the same structure should still be flagged with a high score.

Text to analyze:
"""
$text
"""

Web sources found (URL, snippet):
$sourcesJson

For each suspicious section in the text, determine:
1. Is it an exact copy, partial copy, paraphrase, or semantic similarity?
2. What is the risk level?
3. What is the confidence score?
4. Provide a clear explanation.

Respond ONLY with valid JSON:
{
  "overall_similarity_score": <0-100>,
  "exact_match_score": <0-100>,
  "semantic_similarity_score": <0-100>,
  "paraphrase_score": <0-100>,
  "flagged_sections": [
    {
      "start_position": <char_offset>,
      "end_position": <char_offset>,
      "flagged_text": "<exact text from original>",
      "plagiarism_type": "<exact_copy|partial_copy|semantic_similarity|missing_citation|paraphrased|ai_rewritten>",
      "risk_level": "<safe|low|medium|high|critical>",
      "confidence_score": <0-100>,
      "similarity_score": <0-100>,
      "source_url": "<url>",
      "source_title": "<title>",
      "matched_source_text": "<matching text from source>",
      "explanation": "<why this is flagged>",
      "suggested_action": "<what user should do>"
    }
  ],
  "executive_summary": "<overall assessment>",
  "recommendations": ["<actionable recommendation>"]
}
''';

    try {
      final response = await model.generateContent([Content.text(prompt)]);
      final responseText = response.text ?? '{}';
      print('GeminiService: Received plagiarism response');
      final jsonStr = _extractJson(responseText);
      return jsonDecode(jsonStr) as Map<String, dynamic>;
    } catch (e) {
      print('GeminiService Error (Plagiarism): $e');
      return {
        'overall_similarity_score': 0,
        'exact_match_score': 0,
        'semantic_similarity_score': 0,
        'paraphrase_score': 0,
        'flagged_sections': [],
        'executive_summary': 'Analysis could not be completed at this time.',
        'recommendations': ['Please try again.'],
      };
    }
  }

  /// Rewrite text in a specific style to reduce plagiarism
  Future<Map<String, dynamic>> rewriteText(
    String originalText,
    String style,
  ) async {
    final prompt = '''
Rewrite the following text to eliminate plagiarism while preserving the core meaning.

Style: $style (academic/research/formal/concise/humanized)

Original text:
"""
$originalText
"""

Respond ONLY with valid JSON:
{
  "rewritten_text": "<rewritten version>",
  "changes_made": ["<change description>"],
  "similarity_reduction_estimate": <0-100>,
  "style_notes": "<notes about the style applied>"
}
''';

    try {
      final response = await model.generateContent([Content.text(prompt)]);
      final responseText = response.text ?? '{}';
      print('GeminiService: Received quality analysis response');
      final jsonStr = _extractJson(responseText);
      return jsonDecode(jsonStr) as Map<String, dynamic>;
    } catch (e) {
      print('GeminiService Error (Quality): $e');
      return {
        'rewritten_text': originalText,
        'changes_made': [],
        'similarity_reduction_estimate': 0,
        'style_notes': 'Rewrite failed. Please try again.',
      };
    }
  }

  /// Generate citations for a source
  Future<Map<String, dynamic>> generateCitation(
    Map<String, dynamic> sourceInfo,
  ) async {
    final prompt = '''
Generate academic citations for this source in APA, MLA, IEEE, Harvard, and Chicago styles.

Source information:
${jsonEncode(sourceInfo)}

Respond ONLY with valid JSON:
{
  "apa": "<APA citation>",
  "mla": "<MLA citation>",
  "ieee": "<IEEE citation>",
  "harvard": "<Harvard citation>",
  "chicago": "<Chicago citation>"
}
''';

    try {
      final response = await model.generateContent([Content.text(prompt)]);
      final responseText = response.text ?? '{}';
      print('GeminiService: Received quality analysis response');
      final jsonStr = _extractJson(responseText);
      return jsonDecode(jsonStr) as Map<String, dynamic>;
    } catch (e) {
      print('GeminiService Error (Quality): $e');
      return {
        'apa': 'Citation generation failed.',
        'mla': 'Citation generation failed.',
        'ieee': 'Citation generation failed.',
        'harvard': 'Citation generation failed.',
        'chicago': 'Citation generation failed.',
      };
    }
  }

  /// Detect missing citations in text
  Future<List<Map<String, dynamic>>> detectMissingCitations(
    String text,
  ) async {
    final prompt = '''
Analyze this academic text and identify statements that need citations but lack them.

Text:
"""
$text
"""

Respond ONLY with valid JSON array:
[
  {
    "statement": "<text that needs citation>",
    "reason": "<why it needs a citation>",
    "suggested_search": "<search query to find appropriate source>"
  }
]
''';

    try {
      final response = await model.generateContent([Content.text(prompt)]);
      final responseText = response.text ?? '[]';
      final jsonStr = _extractJsonArray(responseText);
      return (jsonDecode(jsonStr) as List<dynamic>)
          .map((e) => e as Map<String, dynamic>)
          .toList();
    } catch (e) {
      return [];
    }
  }

  /// Compare two documents
  Future<Map<String, dynamic>> compareDocuments(
    String textA,
    String textB,
    String titleA,
    String titleB,
  ) async {
    final prompt = '''
Compare these two documents for similarity, plagiarism, and overlap.

Document A ($titleA):
"""
${textA.length > 3000 ? textA.substring(0, 3000) : textA}
"""

Document B ($titleB):
"""
${textB.length > 3000 ? textB.substring(0, 3000) : textB}
"""

Respond ONLY with valid JSON:
{
  "overall_similarity": <0-100>,
  "exact_match_percentage": <0-100>,
  "semantic_similarity_percentage": <0-100>,
  "paraphrase_percentage": <0-100>,
  "matched_sections": [
    {
      "text_a": "<section from doc A>",
      "text_b": "<matching section from doc B>",
      "similarity_type": "<exact|semantic|paraphrase>",
      "similarity_score": <0-100>
    }
  ],
  "executive_summary": "<overall comparison analysis>",
  "unique_to_a": ["<unique concept/section in A>"],
  "unique_to_b": ["<unique concept/section in B>"]
}
''';

    try {
      final response = await model.generateContent([Content.text(prompt)]);
      final responseText = response.text ?? '{}';
      print('GeminiService: Received quality analysis response');
      final jsonStr = _extractJson(responseText);
      return jsonDecode(jsonStr) as Map<String, dynamic>;
    } catch (e) {
      print('GeminiService Error (Quality): $e');
      return {
        'overall_similarity': 0,
        'exact_match_percentage': 0,
        'semantic_similarity_percentage': 0,
        'paraphrase_percentage': 0,
        'matched_sections': [],
        'executive_summary': 'Comparison failed. Please try again.',
        'unique_to_a': [],
        'unique_to_b': [],
      };
    }
  }

  // Helper to extract JSON from model response
  String _extractJson(String text) {
    final jsonStart = text.indexOf('{');
    final jsonEnd = text.lastIndexOf('}');
    if (jsonStart != -1 && jsonEnd != -1 && jsonEnd > jsonStart) {
      return text.substring(jsonStart, jsonEnd + 1);
    }
    return text.trim();
  }

  String _extractJsonArray(String text) {
    final jsonStart = text.indexOf('[');
    final jsonEnd = text.lastIndexOf(']');
    if (jsonStart != -1 && jsonEnd != -1 && jsonEnd > jsonStart) {
      return text.substring(jsonStart, jsonEnd + 1);
    }
    return '[]';
  }
}
